alter table public.torneio_staff
  add column if not exists id bigint generated by default as identity,
  add column if not exists papel text not null default 'lancador_placar',
  add column if not exists status text not null default 'pendente',
  add column if not exists convite_email text,
  add column if not exists convidado_por_usuario_id uuid references public.profiles (id) on delete set null,
  add column if not exists observacoes text,
  add column if not exists aceito_em timestamptz,
  add column if not exists revogado_em timestamptz;

alter table public.torneio_staff
  alter column usuario_id drop not null;

alter table public.torneio_staff
  drop constraint if exists torneio_staff_pkey;

alter table public.torneio_staff
  add constraint torneio_staff_pkey primary key (id);

create unique index if not exists idx_torneio_staff_unique_usuario
  on public.torneio_staff (torneio_id, usuario_id, papel)
  where usuario_id is not null and status in ('pendente', 'ativo');

create unique index if not exists idx_torneio_staff_unique_email
  on public.torneio_staff (torneio_id, lower(convite_email), papel)
  where convite_email is not null and status in ('pendente', 'ativo');

create index if not exists idx_torneio_staff_torneio_status
  on public.torneio_staff (torneio_id, status, papel);

alter table public.torneio_staff
  drop constraint if exists torneio_staff_papel_ck;

alter table public.torneio_staff
  add constraint torneio_staff_papel_ck
  check (papel in ('lancador_placar'));

alter table public.torneio_staff
  drop constraint if exists torneio_staff_status_ck;

alter table public.torneio_staff
  add constraint torneio_staff_status_ck
  check (status in ('pendente', 'ativo', 'revogado'));

alter table public.torneio_jogos
  add column if not exists lancado_por_usuario_id uuid references public.profiles (id) on delete set null,
  add column if not exists placar_lancado_em timestamptz;
